export interface ReactOptions {
  projectName: string;
}

export function reactPackageJson(opts: ReactOptions): string {
  return JSON.stringify(
    {
      name: `${opts.projectName}-web`,
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'eslint src/ --ext .ts,.tsx',
        format: 'prettier --write "src/**/*.{ts,tsx,css}"',
      },
      dependencies: {
        'next': '^15.0.0',
        'react': '^19.0.0',
        'react-dom': '^19.0.0',
        'zustand': '^5.0.0',
        '@tanstack/react-query': '^5.62.0',
        axios: '^1.7.0',
      },
      devDependencies: {
        '@types/node': '^22.10.0',
        '@types/react': '^19.0.0',
        '@types/react-dom': '^19.0.0',
        'typescript': '^5.7.0',
        'tailwindcss': '^4.0.0',
        '@tailwindcss/postcss': '^4.0.0',
        'postcss': '^8.4.0',
        'eslint': '^9.15.0',
        'prettier': '^3.4.0',
        '@eslint/eslintrc': '^3.2.0',
      },
    },
    null,
    2,
  );
}

export function reactNextConfig(): string {
  return `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  output: 'standalone',
  async rewrites() {
    return [
      {
        source: '/api/:path*',
        destination: 'http://localhost:3000/api/:path*',
      },
    ];
  },
};

export default nextConfig;
`;
}

export function reactTsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2017',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: { '@/*': ['./src/*'] },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules'],
    },
    null,
    2,
  );
}

export function reactPostcssConfig(): string {
  return `export default {
  plugins: {
    '@tailwindcss/postcss': {},
  },
};
`;
}

export function reactGlobalsCss(): string {
  return `@import "tailwindcss";

body {
  margin: 0;
  font-family: Inter, system-ui, -apple-system, sans-serif;
}
`;
}

export function reactLayoutTsx(): string {
  return `import type { Metadata } from 'next';
import { Providers } from '@/components/providers';
import './globals.css';

export const metadata: Metadata = {
  title: 'Fullstack App',
  description: 'Generated by scaffoldify',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
`;
}

export function reactProviders(): string {
  return `'use client';

import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { useState } from 'react';

export function Providers({ children }: { children: React.ReactNode }) {
  const [queryClient] = useState(
    () =>
      new QueryClient({
        defaultOptions: {
          queries: {
            staleTime: 60 * 1000,
            retry: 1,
          },
        },
      }),
  );

  return (
    <QueryClientProvider client={queryClient}>
      {children}
    </QueryClientProvider>
  );
}
`;
}

export function reactHomePage(): string {
  return `'use client';

import { useQuery } from '@tanstack/react-query';
import { userApi } from '@/api/users';
import { useCounterStore } from '@/store/counter';
import Link from 'next/link';

export default function Home() {
  const { count, doubleCount, increment, decrement, reset } = useCounterStore();

  const { data: users, isLoading } = useQuery({
    queryKey: ['users'],
    queryFn: () => userApi.findAll(),
  });

  return (
    <div className="mx-auto flex min-h-screen max-w-5xl flex-col">
      <header className="border-b bg-white">
        <nav className="mx-auto flex max-w-5xl items-center justify-between px-4 py-4">
          <Link href="/" className="text-xl font-bold">
            Fullstack App
          </Link>
          <div className="flex gap-4">
            <Link href="/" className="text-gray-600 hover:text-gray-900">
              Home
            </Link>
            <Link href="/about" className="text-gray-600 hover:text-gray-900">
              About
            </Link>
          </div>
        </nav>
      </header>

      <main className="flex-1 px-4 py-8">
        <div className="space-y-8">
          <section className="text-center">
            <h1 className="text-4xl font-bold text-gray-900">Welcome to Fullstack CLI App</h1>
            <p className="mt-2 text-gray-600">
              Scaffolded with Next.js + Express + Drizzle
            </p>
          </section>

          <section className="rounded-xl border bg-white p-6 shadow-sm">
            <h2 className="mb-4 text-lg font-semibold">Zustand Counter</h2>
            <p className="text-3xl font-bold">{count}</p>
            <p className="text-sm text-gray-500">Double: {doubleCount}</p>
            <div className="mt-3 flex gap-2">
              <button
                onClick={decrement}
                className="rounded bg-gray-200 px-4 py-2 hover:bg-gray-300"
              >
                -
              </button>
              <button
                onClick={increment}
                className="rounded bg-gray-200 px-4 py-2 hover:bg-gray-300"
              >
                +
              </button>
              <button
                onClick={reset}
                className="rounded bg-red-100 px-4 py-2 text-red-600 hover:bg-red-200"
              >
                Reset
              </button>
            </div>
          </section>

          <section className="rounded-xl border bg-white p-6 shadow-sm">
            <h2 className="mb-4 text-lg font-semibold">Users (TanStack Query)</h2>
            {isLoading && <p className="text-gray-400">Loading...</p>}
            <ul className="divide-y">
              {users?.map((user) => (
                <li key={user.id} className="py-2">
                  <p className="font-medium">{user.name}</p>
                  <p className="text-sm text-gray-500">{user.email}</p>
                </li>
              ))}
            </ul>
          </section>
        </div>
      </main>

      <footer className="border-t bg-white py-4 text-center text-sm text-gray-500">
        &copy; {new Date().getFullYear()} Fullstack CLI App
      </footer>
    </div>
  );
}
`;
}

export function reactCounterStore(): string {
  return `import { create } from 'zustand';

interface CounterState {
  count: number;
  doubleCount: number;
  increment: () => void;
  decrement: () => void;
  reset: () => void;
}

export const useCounterStore = create<CounterState>((set, get) => ({
  count: 0,
  doubleCount: 0,
  increment: () => set((state) => ({ count: state.count + 1 })),
  decrement: () => set((state) => ({ count: state.count - 1 })),
  reset: () => set({ count: 0 }),
  doubleCount: 0,
}));

// Derived state: recompute when count changes
useCounterStore.subscribe((state, prevState) => {
  if (state.count !== prevState.count) {
    useCounterStore.setState({ doubleCount: state.count * 2 });
  }
});
`;
}

export function reactApiClient(): string {
  return `import axios from 'axios';

const apiClient = axios.create({
  baseURL: '/api/v1',
  timeout: 10000,
  headers: {
    'Content-Type': 'application/json',
  },
});

apiClient.interceptors.request.use((config) => {
  const token = localStorage.getItem('auth_token');
  if (token) {
    config.headers.Authorization = \`Bearer \${token}\`;
  }
  return config;
});

apiClient.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.status === 401) {
      localStorage.removeItem('auth_token');
    }
    return Promise.reject(error);
  },
);

export default apiClient;
`;
}

export function reactUserApi(): string {
  return `import apiClient from './client';

export interface User {
  id: number;
  name: string;
  email: string;
  bio?: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreateUserDto {
  name: string;
  email: string;
  bio?: string;
}

export const userApi = {
  async findAll() {
    const { data } = await apiClient.get<{ data: User[] }>('/users');
    return data.data;
  },

  async findById(id: number) {
    const { data } = await apiClient.get<{ data: User }>(\`/users/\${id}\`);
    return data.data;
  },

  async create(dto: CreateUserDto) {
    const { data } = await apiClient.post<{ data: User }>('/users', dto);
    return data.data;
  },

  async update(id: number, dto: Partial<CreateUserDto>) {
    const { data } = await apiClient.put<{ data: User }>(\`/users/\${id}\`, dto);
    return data.data;
  },

  async delete(id: number) {
    await apiClient.delete(\`/users/\${id}\`);
  },
};
`;
}
